// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqdvixskvkezycjlvduh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZHZpeHNrdmtlenljamx2ZHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Nzg2ODUsImV4cCI6MjA2ODQ1NDY4NX0.eZLkBVKex0STa1Ioi0Zq6AO3hey475IzR5SKFMVq5Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});